//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amar_Pharmacy1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login1
    {
        public string Email { get; set; }
        public string UserPassword { get; set; }
    }
}
