//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amar_Pharmacy1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlinepharmacyEntities : DbContext
    {
        public OnlinepharmacyEntities()
            : base("name=OnlinepharmacyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryTB1> CategoryTB1 { get; set; }
        public virtual DbSet<MedicineTb1> MedicineTb1 { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
    }
}
